---
- name: Install cryptsetup and dmsetup packages on target hosts
  hosts: all_nodes
  become: true
  tasks:
    - name: Update the package cache (apt-get update)
      apt:
        update_cache: yes

    - name: Install cryptsetup
      apt:
        name: cryptsetup
        state: present

    - name: Install dmsetup
      apt:
        name: dmsetup
        state: present
