# PLAY 1: Fetch the kubeconfig from the master node to the control node
- name: Fetch kubeconfig from master node to control node
  hosts: master_node
  become: yes
  tasks:
    - name: Fetch kubeconfig from master node to control node
      fetch:
        src: "/home/aleksandar/.kube/config"
        dest: "/tmp/kubeconfig_master"
        flat: yes
        validate_checksum: no

# PLAY 2: Distribute the kubeconfig from control node to worker nodes
- name: Setup kubeconfig on worker nodes
  hosts: worker_nodes
  become: yes
  tasks:
    - name: Ensure .kube directory exists
      file:
        path: "/home/aleksandar/.kube"
        state: directory
        owner: "aleksandar"
        group: "aleksandar"
        mode: '0755'

    - name: Copy kubeconfig to worker node
      copy:
        src: "/tmp/kubeconfig_master"
        dest: "/home/aleksandar/.kube/config"
        owner: "aleksandar"
        group: "aleksandar"
        mode: '0644'

    - name: Ensure the kubeconfig server IP is set to master node IP
      lineinfile:
        path: "/home/aleksandar/.kube/config"
        regexp: '^    server:'
        line: "    server: https://192.168.88.242:6443"
        backrefs: yes
      when: update_server_ip | default(True)

    - name: Clean up temporary kubeconfig file on worker node
      file:
        path: "/tmp/kubeconfig_master"
        state: absent
