apiVersion: v1
kind: Service
metadata:
  name: postgres-external           # A service name
  namespace: postgres-db            # Same namespace where PG cluster is running
spec:
  type: LoadBalancer                 # Service type is NodePort, MetalLB
  selector:                          # Targeting pods with the following labels
    cnpg.io/cluster: my-postgres-cluster
    role: primary
  ports:
  - protocol: TCP
    port: 5432                       # PostgreSQL port inside the cluster