apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-redis-pvc
  namespace: nodejs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
